// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SchoolManager.Models
{
    public partial class Grade
    {
        public int Id { get; set; }
        public int? Value { get; set; }
        public int? SubjectId { get; set; }

        public virtual Subject Subject { get; set; }
    }
}