// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SchoolManager.Models
{
    public partial class Student : User
    {
        public Student()
        {
            Subjects = new HashSet<Subject>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public int? ClassId { get; set; }

        public virtual Class Class { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}