// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SchoolManager.Models
{
    public partial class Subject
    {
        public Subject()
        {
            Grades = new HashSet<Grade>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? StudentId { get; set; }

        public virtual Student Student { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
    }
}