// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SchoolManager.Models
{
    public partial class Teacher : User
    {
        public Teacher()
        {
            Classes = new HashSet<Class>();
        }

        public string MainSubject { get; set; }

        public virtual ICollection<Class> Classes { get; set; }
    }
}